branches:
    only:
    - master

script:
- ls index.html #Test it was generated and not deleted.
- ls pages
- ls theme/theme/js/bootstrap.min.js #Specific for my case, the theme was setted correctly.
